### ISSUE TITLE
AttributeError: 'CartpoleRobot' object has no attribute 'getSelf'

### ISSUE THREAD

**Issue by ahforoughi** [aidudezzz/deepbots-tutorials#16]
Hi 
I follow instructions in the repo but got this error:

`Traceback (most recent call last):
  File "supervisorController.py", line 84, in <module>
    env = CartpoleRobot()
  File "supervisorController.py", line 15, in __init__
    self.robot = self.getSelf()  # Grab the robot reference from the supervisor to access various robot methods
AttributeError: 'CartpoleRobot' object has no attribute 'getSelf'
WARNING: 'supervisorController' controller exited with status: 1.`

**Comment by Mayer-eng** [comment]
you might have install two versions of deepbots,and just uninstall one by the command "pip uninstall deepbots" .
