### ISSUE TITLE
Multi robot setting

### ISSUE THREAD

**Issue by juliogodoy** [aidudezzz/deepbots-tutorials#21]
Hi, can deepbots be used in a multi robot setting? (i.e., where each robot has its own controller and interacts with the others)
Thanks,

Julio

**Comment by ManosMagnus** [comment]
Yes, you have two option:

1. You can use `emitter-receiver` [scheme](https://github.com/aidudezzz/deepbots#emitter---receiver-scheme) to broadcast your messages from the supervisor node to the robots. In turn, each robot can receive them by using its receiver. [(Example)](https://github.com/tsampazk/deepworlds/tree/multi-cartpole)   

2. By using `robot-supervisor` [scheme](https://github.com/aidudezzz/deepbots#combined-robot-supervisor-scheme). In this option, every robot has to make its own decision, the communication can be achieved by using either [customData field](https://cyberbotics.com/doc/reference/robot#field-summary)  or [emitter-receiver](hemttps://cyberbotics.com/doc/reference/robot#field-summary)
