### ISSUE TITLE
Emitter-Receiver scheme not working

### ISSUE THREAD

**Issue by Piyush-555** [aidudezzz/deepbots-tutorials#22]
I'm getting following error for `emitterReceiverSchemeTutorial`:
```python
INFO: supervisorController: Starting controller: python -u supervisorController.py
Traceback (most recent call last):
  File "supervisorController.py", line 93, in <module>
    supervisor = CartPoleSupervisor()
  File "supervisorController.py", line 14, in __init__
    self.respawnRobot()
  File "supervisorController.py", line 30, in respawnRobot
    rootNode = self.supervisor.getRoot()  # This gets the root of the scene tree
  File "/usr/local/webots/lib/controller/python37/controller.py", line 2888, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Supervisor, name)
  File "/usr/local/webots/lib/controller/python37/controller.py", line 96, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Supervisor' object has no attribute 'supervisor'
WARNING: 'supervisorController' controller exited with status: 1.
```
I'm using master branch of  deepbots and 2021a version of webots.

**Comment by Piyush-555** [comment]
It seems that this is fixable by replacing `self.supervisor.any_method` with `self.any_method`.  
Is this kept on purpose to support older versions of webots, as stated [here](https://github.com/aidudezzz/deepbots-tutorials/issues/1#issue-607758552) or should I submit a PR?

**Comment by ManosMagnus** [comment]
Excuse me @Piyush-555, I lost this issue in the stack. 

Indeed tutorials aims on latest stable version (not on the latest dev version). Update the tutorials is more than welcome since we are planning to make a major release on the following days

**Comment by ManosMagnus** [comment]
If you are interested I can assigne you on #23

**Comment by ManosMagnus** [comment]
@all-contributors please add @Piyush-555  for bug

**Comment by Piyush-555** [comment]
> If you are interested I can assignee you on #23 

Okay, sounds good.

**Comment by ManosMagnus** [comment]
Please If you are interested, comment on the issue in order in order to assingee to you (github can't find your username in that issue)
