### ISSUE TITLE
Comments on the robotSupervisorSchemeTutorial

### ISSUE THREAD

**Issue by sdu-Hour** [aidudezzz/deepbots-tutorials#25]
AttributeError: 'CartPoleSupervisor' object has no attribute 'supervisor'

this problem come when i open the emitterReceiverSchemeTutorial's world and i am looking for help to solve this problem

**Comment by ManosMagnus** [comment]
Which deepbots version are you using?

**Comment by sdu-Hour** [comment]
i am using the version of R2021a




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Manos ***@***.***&gt;; 
发送时间: 2021年11月29日(星期一) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aidudezzz/deepbots-tutorials] Comments on the robotSupervisorSchemeTutorial (Issue #25)





 
Which deepbots version are you using?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ManosMagnus** [comment]
Ok and which deebots version?

You have to install deepbots in order to run the examples

`pip install deepbots` -> release version `v0.1.2`
`pip install -i https://test.pypi.org/simple/ deepbots` -> dev version `v0.1.3-dev2`

**Comment by sdu-Hour** [comment]
sorry,i am using the version of 0.1.3dev2





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Manos ***@***.***&gt;; 
发送时间: 2021年11月29日(星期一) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aidudezzz/deepbots-tutorials] Comments on the robotSupervisorSchemeTutorial (Issue #25)





 
Which deepbots version are you using?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ManosMagnus** [comment]
I' am afraid that tutorial targets older webots version and works with the release deepbots version. We are working on this

Could you please try to use release version and share if there is an error?

**Comment by ManosMagnus** [comment]
*deebots release version

**Comment by sdu-Hour** [comment]
hello,i'm a&nbsp;graduate student from Shandong university in China.The problem has been solved by install&nbsp;release version&nbsp;v0.1.2(not using 0.1.3dev2 however some examples need 0.1.3dev2).Thank you very much for your letter and help.this would help to my research in&nbsp;Quadruped reinforcement learning.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Manos ***@***.***&gt;; 
发送时间: 2021年11月29日(星期一) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aidudezzz/deepbots-tutorials] Comments on the robotSupervisorSchemeTutorial (Issue #25)





 
I' am afraid that tutorial targets older webots version and works with the release deepbots version. We are working on this
 
Could you please try to use release version and share if there is an error?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ManosMagnus** [comment]
Feel free to contact us if any issue still remains. We will update all the examples on the next few weeks. Sorry for the inconvenience.

Since you working with emitter receiver scheme you can refer on the [deepbots paper](https://citations.springernature.com/item?doi=10.1007/978-3-030-49186-4_6). 

You are more than welcome to open a PR with your example in [deepwords repository](https://github.com/aidudezzz/deepworlds) when is finished. We can provide you extensive code review
