### ISSUE TITLE
NotImplementedError get_info ; 0.1.3 dev2; tutorial

### ISSUE THREAD

**Issue by FengJi2021** [aidudezzz/deepbots-tutorials#26]
I get the NotimplementedError when I run the cartPole tutorial in webot R2022a 
`INFO: robotSupervisorControlle: Starting controller: python.exe -u robotSupervisorControlle.py
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\ReinLearn\mpsees_rel\webot_world\controllers\robotSupervisorControlle\robotSupervisorControlle.py", line 107, in <module>
    newObservation, reward, done, info = env.step([selectedAction])
  File "C:\Python39\lib\site-packages\deepbots\supervisor\controllers\robot_supervisor.py", line 84, in step
    self.get_info(),
  File "C:\Python39\lib\site-packages\deepbots\supervisor\controllers\supervisor_env.py", line 117, in get_info
    raise NotImplementedError
NotImplementedError
WARNING: 'robotSupervisorControlle' controller exited with status: 1`

**Comment by tsampazk** [comment]
You are missing an implementation for the `get_info` method. In [this](https://github.com/aidudezzz/deepbots-tutorials/tree/master/robotSupervisorSchemeTutorial#robotsupervisor-controller-script) section of the tutorial, the last box of code contains dummy implementations of `get_info` and `render` which are needed for the parent classes to function properly.

If you have any further issues, check out the [full project](https://github.com/aidudezzz/deepbots-tutorials/tree/master/robotSupervisorSchemeTutorial/full_project) which contains the completed scripts, and world and compare it with your own to discover any mistakes.

**Comment by FengJi2021** [comment]
I forget to individualize these two dummy functions. you are right

**Comment by tsampazk** [comment]
> I forget to individualize these two dummy functions. you are right

Happy to help!
