### ISSUE TITLE
A small detail

### ISSUE THREAD

**Issue by caozx1110** [aidudezzz/deepbots-tutorials#28]
Hi,

In [robotSupervisorController file](https://github.com/aidudezzz/deepbots-tutorials/blob/master/robotSupervisorSchemeTutorial/full_project/controllers/robotSupervisorController/robotSupervisorController.py), line 111, the code:

`agent.trainStep(batchSize=step)`

does it mean:

`agent.trainStep(batchSize=step + 1)`

or in the [PPO_agent file](https://github.com/aidudezzz/deepbots-tutorials/blob/master/robotSupervisorSchemeTutorial/full_project/controllers/robotSupervisorController/PPO_agent.py), line 145,

it will split the samples into (len - 1) & 1, it seems odd.

Thanks a lot.

**Comment by tsampazk** [comment]
Hey there, i'll take a look at it at the first opportunity i get and get back to you.

**Comment by tsampazk** [comment]
Hey again @caozx1110, you are right! I would say that it is better to do it in robotSupervisorController file instead of the PPO agent file. I'll make the appropriate changes.

@all-contributors please add @caozx1110 for bug

**Comment by caozx1110** [comment]
@tsampazk okk, thanks for your reply 😊😊😊
