### ISSUE TITLE
Unable to run the last step of the tutorial in Webots R2022b.

### ISSUE THREAD

**Issue by NO00636712** [aidudezzz/deepbots-tutorials#32]
The code gets stuck in the environment creation step in the env creation step for both the supervisor and emitter tutorials. I am running Windows 10 and have a pretty decent GPU.

**Comment by KelvinYang0320** [comment]
@NO00636712  Hi, there! Thanks for opening an issue.
Could you provide some screenshots or warning messages to let us reproduce this issue?
Did you install the newest deepbots release (0.1.3)?

**Comment by NO00636712** [comment]
When trying to run the controller script following the rbotSupervisorScheme tutorial I get the message- 

AttributeError: 'CartpoleRobot' object has no attribute 'getSelf'

I have attached the screenshot.
<img width="910" alt="robot_supervisor_error" src="https://user-images.githubusercontent.com/97683408/194805949-ec922c33-665b-4907-9fa2-d38ac0546498.PNG">
Also, I am able to install deepbots 0.1.3-dev using pip, but when I check the python version it shows-0.0.0.11-pre
I have attached the screenshot for this too. 
<img width="746" alt="deepbots_version_error" src="https://user-images.githubusercontent.com/97683408/194805944-a43c233d-6979-4135-8e5a-3de31c5e5b18.PNG">

**Comment by tsampazk** [comment]
Hey @NO00636712, could you try to install deepbots with `pip install -i https://test.pypi.org/simple/ deepbots==0.1.3.dev2` ? It should give you the latest stable dev release.
