### ISSUE TITLE
A doubt for behaviors that the agent finally converged

### ISSUE THREAD

**Issue by speedhawk** [aidudezzz/deepbots-tutorials#39]
Hi, Sorry to trouble you again. In recent months I implemented a 'find-and-avoid' project by myself according to the thought of yours at the algorithm parts and other papers I read at the reward parts. However, the agent finally keeps going around in circles. After checking repeatedly I think the most possible reason is the reward sparsity which commonly leads to poor exploration so that the behaviors fall into the local optimal paradox. Based on this, I hope to discuss two questions with you, hope this will not spend you too much time!
Q1. Based on your experiences, how effectively it can be improved if I deploy the curiosity-driving learning to solve the poverty exploration?
Q2. I found another factor differing from yours is the action mask. By now I still not deploy this method yet. But may I ask you how many it can be improved if this method achieves?
Thank you very much! I'll wait for your reply.

**Comment by tsampazk** [comment]
Closing this as it is more well-suited for deepworlds https://github.com/aidudezzz/deepworlds/issues/96
