### ISSUE TITLE
Link for cartpole_robot_definition.txt is not working

### ISSUE THREAD

**Issue by AlboAlby00** [aidudezzz/deepbots-tutorials#40]
I'm trying to follow the tutorial, but it seems that the link for the cartpole_robot_definition.txt is not working. (Not a big problem though, since the file can be found in the full_project directory here https://github.com/aidudezzz/deepbots-tutorials/blob/update-emitter-receiver-tutorial/robotSupervisorSchemeTutorial/full_project/controllers/robot_supervisor_controller/cartpole_robot_definition.txt

**Comment by tsampazk** [comment]
Hi @AlboAlby00, thanks for reporting this. The link is indeed broken due to a directory renaming. The working link you provided is actually from a branch, but serves its purpose for a quick workaround.

I am merging a fix soon, thank you very much! 😄

**Comment by tsampazk** [comment]
Should be fixed now.
